version: '3.7'
services:
  goapp:
    image: yasser583/goapp:ultima
    container_name: 'goapp'
    network_mode: host

  prometheus:
    image: prom/prometheus
    depends_on:
      - goapp
    container_name: 'prometheus'
    network_mode: host
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    container_name: 'grafana'
    network_mode: host
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    restart: always
