apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
- name: Prometheus
  type: prometheus
  orgId: 1
  url: http://localhost:9090
  access: server
  basicAuth: false
  jsonData:
    graphiteVersion: "1.1"
    tlsAuth: false
    tlsAuthWithCACert: false
  isDefault: true
  version: 1
  editable: true
